init

diff --git a/local/binary/konvert_img_dat b/local/binary/konvert_img_dat
--- a/local/binary/konvert_img_dat
+++ b/local/binary/konvert_img_dat
@@ -1,162 +1,160 @@
 #!/system/bin/sh
 
-myk(){
- read b
- if [ "$b" -le "7" ]; then
- echo ".....Конвертация в "$file".br...Ждём..."
- brotli -"$b"f ./"$file"
- echo
- else
- echo
- echo ".....Вводите цифру от 0 до 7:"
- myk
- echo
- fi
- if [ $(echo $?) -eq 0 ] ; then
- #echo
- echo ".....Успешно завершена конвертация в .br!"
- echo "$print_size_out"
- echo "$print_size_free"
- #echo
- busybox rm -f "$file"
- else
- #echo
- echo ".....error: Ошибка при конвертации в .br!"
- echo
- fi
-return
+myk() {
+	read b
+	if [ "$b" -le "7" ]; then
+		echo ".....Конвертация в "$file".br...Ждём..."
+		brotli -"$b"f ./"$file"
+		echo
+	else
+		echo
+		echo ".....Вводите цифру от 0 до 7:"
+		myk
+		echo
+	fi
+	if [ $(echo $?) -eq 0 ]; then
+		#echo
+		echo ".....Успешно завершена конвертация в .br!"
+		echo "$print_size_out"
+		echo "$print_size_free"
+		#echo
+		busybox rm -f "$file"
+	else
+		#echo
+		echo ".....error: Ошибка при конвертации в .br!"
+		echo
+	fi
+	return
 }
 
-br_conv()
-{
- if [ -f ./"$file" ]; then
- echo
- echo ".....Конвертация в .br..."
- echo ".....Введите степень сжатия(цифру от 0 до 7):"
- myk
- else
- echo
- echo ".....В папке нет "$file"."
- echo
- fi
-return
+br_conv() {
+	if [ -f ./"$file" ]; then
+		echo
+		echo ".....Конвертация в .br..."
+		echo ".....Введите степень сжатия(цифру от 0 до 7):"
+		myk
+	else
+		echo
+		echo ".....В папке нет "$file"."
+		echo
+	fi
+	return
 }
 
+r="$(busybox basename $file)"
+img_name=${r%.*}
 
- r="$(busybox basename $file)"
- img_name=${r%.*}
-
- if [ -f ./"$file" ]; then
- if [ ! -z "$(busybox hexdump -C -n 4 ./"$file" | grep '3a ff 26 ed')" ]; then
- if busybox test -s "$file"; then
- f_name="$(echo "$file" | busybox awk -F"." '{ print $1 }')"
-size_out="$(busybox hexdump -C -n 50 "$file" | busybox awk '{if($1==00000000) {b="0x"$17$16$15$14}} {if($1==00000010) {a="0x"$5$4$3$2}}
+if [ -f ./"$file" ]; then
+	if [ ! -z "$(busybox hexdump -C -n 4 ./"$file" | grep '3a ff 26 ed')" ]; then
+		if busybox test -s "$file"; then
+			f_name="$(echo "$file" | busybox awk -F"." '{ print $1 }')"
+			size_out="$(busybox hexdump -C -n 50 "$file" | busybox awk '{if($1==00000000) {b="0x"$17$16$15$14}} {if($1==00000010) {a="0x"$5$4$3$2}}
 END {print a*b}')"
 
- print_size_out="$(echo ".....Размер raw == $size_out байт")"
+			print_size_out="$(echo ".....Размер raw == $size_out байт")"
 
-busybox dd if="$file" ibs=1 skip=40 of="$f_name".size.img bs=1 count=65536 &> /dev/null
-size_free="$(busybox expr "$(tune2fs -l "$f_name".size.img 2> /dev/null | busybox awk '/Free blocks:/ { print $3 }')" \* 4096 / 1024 / 1024 2> /dev/null)"
- if [ $(echo $?) -eq 0 ]; then
- 
- print_size_free=$(echo ".....Свободное место: $size_free мб")
- else
- print_size_free=$(echo ".....Свободное место: Не определено")
- fi
- fi
+			busybox dd if="$file" ibs=1 skip=40 of="$f_name".size.img bs=1 count=65536 &>/dev/null
+			size_free="$(busybox expr "$(tune2fs -l "$f_name".size.img 2>/dev/null | busybox awk '/Free blocks:/ { print $3 }')" \* 4096 / 1024 / 1024 2>/dev/null)"
+			if [ $(echo $?) -eq 0 ]; then
 
- echo
- echo ".....Конвертация "$file" -> "$img_name".new.dat..."
- echo
- echo ".....Введите цифру, соответствующую версию андроида, собираемого образа:"
-echo
- python31 /data/local/binary/bin_system/img2sdat-master/img2sdat5.py ./"$file"
-if [ $(echo $?) -eq 0 ] ; then
-echo
-echo ".....Успешно завершена конвертация в .dat!"
-#echo
- if [ "$br_check" == "true" ]; then
- file=./"$img_name".new.dat
- br_conv
- else
- echo "$print_size_out"
- echo "$print_size_free"
- #echo
- fi
+				print_size_free=$(echo ".....Свободное место: $size_free мб")
+			else
+				print_size_free=$(echo ".....Свободное место: Не определено")
+			fi
+		fi
+
+		echo
+		echo ".....Конвертация "$file" -> "$img_name".new.dat..."
+		echo
+		echo ".....Введите цифру, соответствующую версию андроида, собираемого образа:"
+		echo
+		python31 /data/local/binary/bin_system/img2sdat-master/img2sdat5.py ./"$file"
+		if [ $(echo $?) -eq 0 ]; then
+			echo
+			echo ".....Успешно завершена конвертация в .dat!"
+			#echo
+			if [ "$br_check" == "true" ]; then
+				file=./"$img_name".new.dat
+				br_conv
+			else
+				echo "$print_size_out"
+				echo "$print_size_free"
+			#echo
+			fi
+		else
+			echo
+			echo ".....error: Ошибка при конвертации в .dat!"
+			echo
+		fi
+
+	elif [ ! -z "$(busybox hexdump -C -n 2000 "$file" | busybox awk '/00000430/ { print $10$11 }' | busybox grep "53ef")" -o ! -z "$(busybox hexdump -C -n 20000 "$file" | busybox grep -o "30 50 4c 41")" -o ! -z "$(busybox hexdump -C -n 2000 "$file" | busybox awk '/00000400/ { print $2$3$4$5 }' | busybox grep -o "e2e1f5e0")" ]; then
+
+		if busybox test -s "$file"; then
+			size_out="$(busybox stat -c %s "$file")"
+			print_size_out="$(echo ".....Размер raw == $size_out байт")"
+			size_free="$(busybox expr "$(tune2fs -l "$file" 2>/dev/null | busybox awk '/Free blocks:/ { print $3 }')" \* 4096 / 1024 / 1024 2>/dev/null)"
+			if [ $(echo $?) -eq 0 ]; then
+
+				print_size_free=$(echo ".....Свободное место: $size_free мб")
+			else
+				print_size_free=$(echo ".....Свободное место: Не определено")
+			fi
+		fi
+		echo
+		echo ".....Конвертация "$img_name".img -> "$img_name".sparse.img..."
+		#echo
+		img2simg ./"$file" ./"$img_name".sparse.img 2>/dev/nul
+		if [ $(echo $?) -eq 0 ]; then
+			echo
+			echo ".....Успешно завершена конвертация в sparse!"
+			echo
+
+			if [ ! -z "$(busybox hexdump -C -n 4 ./"$img_name".sparse.img | busybox grep '3a ff 26 ed')" ]; then
+				#clear
+				echo
+				echo ".....Конвертация "$img_name".sparse.img -> "$img_name".new.dat..."
+				echo
+				echo ".....Введите цифру, соответствующую версию андроида, собираемого образа:"
+				echo
+				python31 /data/local/binary/bin_system/img2sdat-master/img2sdat5.py ./"$img_name".sparse.img
+				if [ $(echo $?) -eq 0 ]; then
+
+					busybox mv -f ./"$img_name".sparse.new.dat ./"$img_name".new.dat
+					busybox mv -f ./"$img_name".sparse.patch.dat ./"$img_name".patch.dat
+					busybox mv -f ./"$img_name".sparse.transfer.list ./"$img_name".transfer.list
+					echo
+					echo ".....Успешно завершена конвертация в .dat!"
+					#echo
+					if [ "$br_check" == "true" ]; then
+						file=./"$img_name".new.dat
+						br_conv
+					else
+						echo "$print_size_out"
+						echo "$print_size_free"
+					#echo
+					fi
+				else
+					echo
+					echo ".....error: Ошибка при конвертации в .dat!"
+					echo
+				fi
+			else
+				echo
+				echo ".....Ошибка при конвертации в sparse!"
+				echo
+			fi
+
+		else
+			echo
+			echo ".....Конвертация "$file" не поддерживается!"
+			echo
+		fi
+	fi
 else
-echo
-echo ".....error: Ошибка при конвертации в .dat!"
-echo
+	echo
+	echo ".....В папке нет образа \""$file"\" для конвертации."
 fi
-
-elif [ ! -z "$(busybox hexdump -C -n 2000 "$file" | busybox awk '/00000430/ { print $10$11 }' | busybox grep "53ef")" -o ! -z "$(busybox hexdump -C -n 20000 "$file" | busybox grep -o "30 50 4c 41")" -o ! -z "$(busybox hexdump -C -n 2000 "$file" | busybox awk '/00000400/ { print $2$3$4$5 }' | busybox grep -o "e2e1f5e0")" ]; then
-
-if busybox test -s "$file"; then
- size_out="$(busybox stat -c %s "$file")"
- print_size_out="$(echo ".....Размер raw == $size_out байт")"
- size_free="$(busybox expr "$(tune2fs -l "$file" 2> /dev/null | busybox awk '/Free blocks:/ { print $3 }')" \* 4096 / 1024 / 1024 2> /dev/null)"
- if [ $(echo $?) -eq 0 ]; then
- 
- print_size_free=$(echo ".....Свободное место: $size_free мб")
- else
- print_size_free=$(echo ".....Свободное место: Не определено")
- fi
- fi
-echo
-echo ".....Конвертация "$img_name".img -> "$img_name".sparse.img..."
-#echo
-img2simg ./"$file" ./"$img_name".sparse.img 2> /dev/nul
- if [ $(echo $?) -eq 0 ]; then
-echo
-echo ".....Успешно завершена конвертация в sparse!"
-echo
- 
- if [ ! -z "$(busybox hexdump -C -n 4 ./"$img_name".sparse.img | busybox grep '3a ff 26 ed')" ]; then
- #clear
- echo
- echo ".....Конвертация "$img_name".sparse.img -> "$img_name".new.dat..."
- echo
- echo ".....Введите цифру, соответствующую версию андроида, собираемого образа:"
-echo
- python31 /data/local/binary/bin_system/img2sdat-master/img2sdat5.py ./"$img_name".sparse.img
-if [ $(echo $?) -eq 0 ]; then
-
- busybox mv -f ./"$img_name".sparse.new.dat ./"$img_name".new.dat
- busybox mv -f ./"$img_name".sparse.patch.dat ./"$img_name".patch.dat
- busybox mv -f ./"$img_name".sparse.transfer.list ./"$img_name".transfer.list
-echo
-echo ".....Успешно завершена конвертация в .dat!"
-#echo
- if [ "$br_check" == "true" ]; then
- file=./"$img_name".new.dat
- br_conv
- else
- echo "$print_size_out"
- echo "$print_size_free"
- #echo
- fi
-  else
-echo
-echo ".....error: Ошибка при конвертации в .dat!"
-echo
- fi
- else
-echo
-echo ".....Ошибка при конвертации в sparse!"
-echo
-fi
-
-else
-echo
-echo ".....Конвертация "$file" не поддерживается!"
-echo
-fi
-fi
-else
-echo
-echo ".....В папке нет образа \""$file"\" для конвертации."
-fi
- busybox rm -f /data/local/python31/tmp* tmp* "$img_name".sparse.img
+busybox rm -f /data/local/python31/tmp* tmp* "$img_name".sparse.img
 
 unset size_out
 unset size_free
diff --git a/local/binary/pack_img_dat b/local/binary/pack_img_dat
--- a/local/binary/pack_img_dat
+++ b/local/binary/pack_img_dat
@@ -2,160 +2,155 @@
 
 clear
 #cd /data/local/UnpackerSystem
- pack_d="$pack_d"
+pack_d="$pack_d"
 
- 
- . /data/local/binary/pack_img
+. /data/local/binary/pack_img
 
 #----------------------------finish pack
 
 if busybox test -s "$outdir"/"$pack_d".new.img; then
 
- mv_dat()
-{
- busybox test -s "$outdir"/"$pack_d".new.new.dat && busybox mv -f "$outdir"/"$pack_d".new.new.dat "$outdir"/"$pack_d".new.dat
- busybox test -f "$outdir"/"$pack_d".new.patch.dat && busybox mv -f "$outdir"/"$pack_d".new.patch.dat "$outdir"/"$pack_d".patch.dat
- busybox test -s "$outdir"/"$pack_d".new.transfer.list && busybox mv -f "$outdir"/"$pack_d".new.transfer.list "$outdir"/"$pack_d".transfer.list
-}
+	mv_dat() {
+		busybox test -s "$outdir"/"$pack_d".new.new.dat && busybox mv -f "$outdir"/"$pack_d".new.new.dat "$outdir"/"$pack_d".new.dat
+		busybox test -f "$outdir"/"$pack_d".new.patch.dat && busybox mv -f "$outdir"/"$pack_d".new.patch.dat "$outdir"/"$pack_d".patch.dat
+		busybox test -s "$outdir"/"$pack_d".new.transfer.list && busybox mv -f "$outdir"/"$pack_d".new.transfer.list "$outdir"/"$pack_d".transfer.list
+	}
 
-b="python31 /data/local/binary/bin_system/img2sdat-master/img2sdat5.py "$outdir"/"$pack_d".new.img $outdir"
-if [ -d ./"$pack_d" ]; then
-#a=$(busybox awk -F"=" '/ro.build.version.release=/ { print $2 }' "$pack_d"/build.prop 2> /dev/null)
+	b="python31 /data/local/binary/bin_system/img2sdat-master/img2sdat5.py "$outdir"/"$pack_d".new.img $outdir"
+	if [ -d ./"$pack_d" ]; then
+		#a=$(busybox awk -F"=" '/ro.build.version.release=/ { print $2 }' "$pack_d"/build.prop 2> /dev/null)
 
-#a1=$(busybox awk -F"=" '/ro.build.version.release=/ { print $2 }' "$pack_d"/"$pack_d"/build.prop 2> /dev/null)
-#if [ -z "$a" ]; then
-#a="$a1"
-#else
-#a="$a"
-#fi
+		#a1=$(busybox awk -F"=" '/ro.build.version.release=/ { print $2 }' "$pack_d"/"$pack_d"/build.prop 2> /dev/null)
+		#if [ -z "$a" ]; then
+		#a="$a1"
+		#else
+		#a="$a"
+		#fi
 
+		a=$(busybox awk -F"=" '/ro.build.version.release=/ { print $2 }' "$pack_d"/build.prop 2>/dev/null) || a=$(busybox awk -F"=" '/ro.build.version.release=/ { print $2 }' "$pack_d"/system/build.prop 2>/dev/null)
 
-a=$(busybox awk -F"=" '/ro.build.version.release=/ { print $2 }' "$pack_d"/build.prop 2> /dev/null) || a=$(busybox awk -F"=" '/ro.build.version.release=/ { print $2 }' "$pack_d"/system/build.prop 2> /dev/null)
+		g=$(busybox grep 'ro.build.version.sdk=.*.' /data/local/UnpackerSystem/"$pack_d"/build.prop | busybox grep -Eo '.{2}$') 2>/dev/null || g=$(busybox grep 'ro.build.version.sdk=.*.' "$pack_d"/system/build.prop | busybox grep -Eo '.{2}$') 2>/dev/null
+		if [ "$g" -ge "24" ]; then
+			echo
+			echo "......Обнаружена версия АРI = $g Версия андроид: $a"
+			echo
+			echo "......Конвертация в .dat..."
+			echo
+			$b 4
+			if [ $(echo $?) -eq 0 ]; then
+				mv_dat
+				echo
+				echo ".....Успешно завершено!"
+				echo
+				echo ".....Размер raw == $size_out байт"
+				echo ".....Свободное место: $size_free мб"
+				echo
+				#echo ".....Удаление "$pack_d".new.img..."
+				rm -f "$outdir"/"$pack_d".new.img
+			#echo
+			else
+				echo
+				echo ".....error: Ошибка при конвертации."
+				echo
+			fi
 
+		elif [ "$g" -eq "21" ]; then
+			echo
+			echo "......Обнаружена версия АРI = $g Версия андроид: $a"
+			echo
+			echo "......Конвертация в .dat..."
+			echo
+			$b 1
+			if [ $(echo $?) -eq 0 ]; then
+				mv_dat
+				echo
+				echo ".....Успешно завершено!"
+				echo
+				echo ".....Размер raw == $size_out байт"
+				echo ".....Свободное место: $size_free мб"
+				echo
+				#echo ".....Удаление "$pack_d".new.img..."
+				rm -f "$outdir"/"$pack_d".new.img
+			#echo
+			else
+				echo
+				echo ".....error: Ошибка при конвертации."
+				echo
+			fi
 
-g=$(busybox grep 'ro.build.version.sdk=.*.' /data/local/UnpackerSystem/"$pack_d"/build.prop | busybox grep -Eo '.{2}$') 2> /dev/null || g=$(busybox grep 'ro.build.version.sdk=.*.' "$pack_d"/system/build.prop | busybox grep -Eo '.{2}$') 2> /dev/null
-if [ "$g" -ge "24" ]; then
-echo
-echo "......Обнаружена версия АРI = $g Версия андроид: $a"
-echo
-echo "......Конвертация в .dat..."
-echo
-$b 4
-if [ $(echo $?) -eq 0 ]; then
- mv_dat
-echo
-echo ".....Успешно завершено!"
-echo
-echo ".....Размер raw == $size_out байт"
-echo ".....Свободное место: $size_free мб"
-echo
-#echo ".....Удаление "$pack_d".new.img..."
-rm -f "$outdir"/"$pack_d".new.img
-#echo
+		elif [ "$g" -eq "22" ]; then
+			echo
+			echo "......Обнаружена версия АРI = $g Версия андроид: $a"
+			echo
+			echo "......Конвертация в .dat..."
+			echo
+			$b 2
+			if [ $(echo $?) -eq 0 ]; then
+				mv_dat
+				echo
+				echo ".....Успешно завершено!"
+				echo
+				echo ".....Размер raw == $size_out байт"
+				echo ".....Свободное место: $size_free мб"
+				echo
+				#echo ".....Удаление "$pack_d".new.img..."
+				rm -f "$outdir"/"$pack_d".new.img
+			#echo
+			else
+				echo
+				echo ".....error: Ошибка при конвертации."
+				echo
+			fi
+
+		elif [ "$g" -eq "23" ]; then
+			echo
+			echo "......Обнаружена версия АРI = $g Версия андроид: $a"
+			echo
+			echo "......Конвертация в .dat..."
+			echo
+			$b 3
+			if [ $(echo $?) -eq 0 ]; then
+				mv_dat
+				echo
+				echo ".....Успешно завершено!"
+				echo
+				echo ".....Размер raw == $size_out байт"
+				echo ".....Свободное место: $size_free мб"
+				echo
+				#echo ".....Удаление "$pack_d".new.img..."
+				rm -f "$outdir"/"$pack_d".new.img
+			#echo
+			else
+				echo
+				echo ".....error: Ошибка при конвертации."
+				echo
+			fi
+
+		else
+			echo ".....Не найдена версия SDK."
+			echo
+			echo ".....Введите цифру, соответствующую версии андроида, собираемого образа:"
+			echo
+			$b
+			if [ $(echo $?) -eq 0 ]; then
+				mv_dat # функция переименования
+				echo
+				echo ".....Успешно завершено!"
+				echo
+				echo ".....Размер raw == $size_out байт"
+				echo ".....Свободное место: $size_free мб"
+				echo
+				#echo ".....Удаление "$pack_d".new.img..."
+				rm -f "$outdir"/"$pack_d".new.img
+			#echo
+			else
+				echo
+				echo ".....error: Ошибка при конвертации!"
+				echo
+			fi
+		fi
+	fi
 else
-echo
-echo ".....error: Ошибка при конвертации."
-echo
+	echo ".....Нет образa \""$pack_d".new.img\" для конвертации."
 fi
-
-elif [ "$g" -eq "21" ]; then
-echo
-echo "......Обнаружена версия АРI = $g Версия андроид: $a"
-echo
-echo "......Конвертация в .dat..."
-echo
-$b 1
-if [ $(echo $?) -eq 0 ]; then
- mv_dat
-echo
-echo ".....Успешно завершено!"
-echo
-echo ".....Размер raw == $size_out байт"
-echo ".....Свободное место: $size_free мб"
-echo
-#echo ".....Удаление "$pack_d".new.img..."
-rm -f "$outdir"/"$pack_d".new.img
-#echo
-else
-echo
-echo ".....error: Ошибка при конвертации."
-echo
-fi
-
-elif [ "$g" -eq "22" ]; then
-echo
-echo "......Обнаружена версия АРI = $g Версия андроид: $a"
-echo
-echo "......Конвертация в .dat..."
-echo
-$b 2
-if [ $(echo $?) -eq 0 ]; then
- mv_dat
-echo
-echo ".....Успешно завершено!"
-echo
-echo ".....Размер raw == $size_out байт"
-echo ".....Свободное место: $size_free мб"
-echo
-#echo ".....Удаление "$pack_d".new.img..."
-rm -f "$outdir"/"$pack_d".new.img
-#echo
-else
-echo
-echo ".....error: Ошибка при конвертации."
-echo
-fi
-
-elif [ "$g" -eq "23" ]; then
-echo
-echo "......Обнаружена версия АРI = $g Версия андроид: $a"
-echo
-echo "......Конвертация в .dat..."
-echo
-$b 3
-if [ $(echo $?) -eq 0 ]; then
- mv_dat
-echo
-echo ".....Успешно завершено!"
-echo
-echo ".....Размер raw == $size_out байт"
-echo ".....Свободное место: $size_free мб"
-echo
-#echo ".....Удаление "$pack_d".new.img..."
-rm -f "$outdir"/"$pack_d".new.img
-#echo
-else
-echo
-echo ".....error: Ошибка при конвертации."
-echo
-fi
-
-else
-echo ".....Не найдена версия SDK."
-echo
-echo ".....Введите цифру, соответствующую версии андроида, собираемого образа:"
-echo
-$b
-if [ $(echo $?) -eq 0 ]; then
- mv_dat # функция переименования
-echo
-echo ".....Успешно завершено!"
-echo
-echo ".....Размер raw == $size_out байт"
-echo ".....Свободное место: $size_free мб"
-echo
-#echo ".....Удаление "$pack_d".new.img..."
-rm -f "$outdir"/"$pack_d".new.img
-#echo
-else
-echo
-echo ".....error: Ошибка при конвертации!"
-echo
-fi
-fi
-fi
-else
-echo ".....Нет образa \""$pack_d".new.img\" для конвертации."
-fi
- rm -f /data/local/python31/tmp* tmp*
-
+rm -f /data/local/python31/tmp* tmp*
diff --git a/local/binary/pack_img_e2fsdroid b/local/binary/pack_img_e2fsdroid
--- a/local/binary/pack_img_e2fsdroid
+++ b/local/binary/pack_img_e2fsdroid
@@ -1,151 +1,149 @@
 #!/system/bin/sh
 
-
- size_output_raw()
-{
- if busybox test -s "$outdir"/"$pack_d".new.img; then
- echo
- echo -e "\033[33;1m.....Успешно создан "$pack_d".new.img!\033[0m"
- echo
- #if [ "$sparse_e2fs" == "1" ]; then
- #size_out="$size_out"
- #else
- #size_out="$(busybox stat -c %s "$outdir"/"$pack_d".new.img)"
- #fi
- echo "$size_out" > "$config"/"$pack_d"_size_out.txt
- echo -e "\033[33;1m.....Размер raw == $size_out байт\033[0m"
- echo
-fi
- return
+size_output_raw() {
+	if busybox test -s "$outdir"/"$pack_d".new.img; then
+		echo
+		echo -e "\033[33;1m.....Успешно создан "$pack_d".new.img!\033[0m"
+		echo
+		#if [ "$sparse_e2fs" == "1" ]; then
+		#size_out="$size_out"
+		#else
+		#size_out="$(busybox stat -c %s "$outdir"/"$pack_d".new.img)"
+		#fi
+		echo "$size_out" >"$config"/"$pack_d"_size_out.txt
+		echo -e "\033[33;1m.....Размер raw == $size_out байт\033[0m"
+		echo
+	fi
+	return
 }
 
-gen_avb_key()
-{
-if busybox test ! -f "$dir_avb"/"$pack_d"_"$rs"_new_private.pem; then
-   echo
-   echo ".....Генерация ключа AVB..."
-   #echo
-   openssl genpkey -algorithm RSA -pkeyopt rsa_keygen_bits:"$rs" -outform PEM -out "$dir_avb"/"$pack_d"_"$rs"_new_private.pem 2> /dev/null
+gen_avb_key() {
+	if busybox test ! -f "$dir_avb"/"$pack_d"_"$rs"_new_private.pem; then
+		echo
+		echo ".....Генерация ключа AVB..."
+		#echo
+		openssl genpkey -algorithm RSA -pkeyopt rsa_keygen_bits:"$rs" -outform PEM -out "$dir_avb"/"$pack_d"_"$rs"_new_private.pem 2>/dev/null
 
- avbtool extract_public_key --key "$dir_avb"/"$pack_d"_"$rs"_new_private.pem --output "$dir_avb"/"$pack_d"_"$rs"_new_pubkey.pem
- fi
- sign_file="--key "$dir_avb"/"$pack_d"_"$rs"_new_private.pem"
- sign_print="--algorithm $check_alg"
- 
- return
+		avbtool extract_public_key --key "$dir_avb"/"$pack_d"_"$rs"_new_private.pem --output "$dir_avb"/"$pack_d"_"$rs"_new_pubkey.pem
+	fi
+	sign_file="--key "$dir_avb"/"$pack_d"_"$rs"_new_private.pem"
+	sign_print="--algorithm $check_alg"
+
+	return
 }
 
+baze_dir=/data/local/UnpackerSystem
+dir_avb=/data/local/UnpackerSystem/config/"$pack_d"
+config="config/$pack_d"
+img_name=$(cat /data/local/UnpackerSystem/"$config"/"$pack_d"*_name.txt)
 
- baze_dir=/data/local/UnpackerSystem
- dir_avb=/data/local/UnpackerSystem/config/"$pack_d"
- config="config/$pack_d"
- img_name=$(cat /data/local/UnpackerSystem/"$config"/"$pack_d"*_name.txt)
- 
- 
- razn="$(busybox expr "$(busybox du -s "$pack_d" | busybox awk '{ print $1 }')" \* 1024 - "$(busybox cat "$config"/"$pack_d"_size_papka.txt)")"
+razn="$(busybox expr "$(busybox du -s "$pack_d" | busybox awk '{ print $1 }')" \* 1024 - "$(busybox cat "$config"/"$pack_d"_size_papka.txt)")"
 
- size_tmp="$(busybox expr "$(busybox cat "$dir_avb"/"$pack_d"_size.txt)" \* 41 / 39 \+ "$razn")"
+size_tmp="$(busybox expr "$(busybox cat "$dir_avb"/"$pack_d"_size.txt)" \* 41 / 39 \+ "$razn")"
 
- size_obraz="$(busybox expr "$size_tmp" / 4096 \* 4096)"
+size_obraz="$(busybox expr "$size_tmp" / 4096 \* 4096)"
 
- #size_avb="$(avbtool add_hashtree_footer --partition_size "$size_obraz" --do_not_generate_fec --calc_max_image_size)"
+#size_avb="$(avbtool add_hashtree_footer --partition_size "$size_obraz" --do_not_generate_fec --calc_max_image_size)"
 
+. /data/local/binary/perm_fs
 
- 
- . /data/local/binary/perm_fs
-
- unset check_alg
- unset sign_file
- unset sign_print
- #size_obraz="$(busybox cat "$dir_avb"/"$pack_d"_size.txt)"
- if busybox test -s "$dir_avb"/"$pack_d"_avb.img; then
- prop_avb="$(busybox cat "$dir_avb"/"$pack_d"_avb.img | busybox awk '/    Prop:/ { print "--prop"" "$2":"$4 }' | tr '\n' ' ')"
- check_alg="$(busybox cat "$dir_avb"/"$pack_d"_avb.img | busybox awk '/^Algorithm:/ { print $2 }')"
- if [ "$check_alg" != "NONE" -a ! -z "$check_alg" ]; then
- case "$check_alg" in
-   "SHA256_RSA2048" ) rs="2048"
-   gen_avb_key ;;
-   "SHA256_RSA4096" ) rs="4096"
-   gen_avb_key ;;
-   "SHA256_RSA8192" ) rs="8192"
-   gen_avb_key ;;
- esac
-#else
-#sign_print=""
-#sign_file=""
+unset check_alg
+unset sign_file
+unset sign_print
+#size_obraz="$(busybox cat "$dir_avb"/"$pack_d"_size.txt)"
+if busybox test -s "$dir_avb"/"$pack_d"_avb.img; then
+	prop_avb="$(busybox cat "$dir_avb"/"$pack_d"_avb.img | busybox awk '/    Prop:/ { print "--prop"" "$2":"$4 }' | tr '\n' ' ')"
+	check_alg="$(busybox cat "$dir_avb"/"$pack_d"_avb.img | busybox awk '/^Algorithm:/ { print $2 }')"
+	if [ "$check_alg" != "NONE" -a ! -z "$check_alg" ]; then
+		case "$check_alg" in
+		"SHA256_RSA2048")
+			rs="2048"
+			gen_avb_key
+			;;
+		"SHA256_RSA4096")
+			rs="4096"
+			gen_avb_key
+			;;
+		"SHA256_RSA8192")
+			rs="8192"
+			gen_avb_key
+			;;
+		esac
+	#else
+	#sign_print=""
+	#sign_file=""
+	fi
+	part_name_tmp="$(busybox cat "$dir_avb"/"$pack_d"_part_name.txt)"
+	if busybox test ! -z "$part_name_tmp"; then
+		part_name="$(busybox cat "$dir_avb"/"$pack_d"_part_name.txt | busybox awk '{ print "--partition_name"" "$0 }')"
+	else
+		part_name=""
+	fi
 fi
- part_name_tmp="$(busybox cat "$dir_avb"/"$pack_d"_part_name.txt)"
- if busybox test ! -z "$part_name_tmp"; then
- part_name="$(busybox cat "$dir_avb"/"$pack_d"_part_name.txt | busybox awk '{ print "--partition_name"" "$0 }')"
- else
- part_name=""
- fi
- fi
 
+if [ -d ./"$pack_d" -a -f ./"$config"/"$pack_d"*_pack_e2fsdroid.sh ]; then
 
- if [ -d ./"$pack_d" -a -f ./"$config"/"$pack_d"*_pack_e2fsdroid.sh ]; then
- 
-if [ -f ./"$config"/"$pack_d"*_fs_config_e2fsdroid -a -f ./"$config"/"$pack_d"*_file_contexts ]; then
+	if [ -f ./"$config"/"$pack_d"*_fs_config_e2fsdroid -a -f ./"$config"/"$pack_d"*_file_contexts ]; then
 
-echo
-echo
-echo ".....Создание образа "$pack_d".new.img..."
-echo
-chmod 755 ./"$config"/"$pack_d"_pack_e2fsdroid.sh && . ./"$config"/"$pack_d"*_pack_e2fsdroid.sh
- if [ $(echo $?) -eq 0 ]; then
+		echo
+		echo
+		echo ".....Создание образа "$pack_d".new.img..."
+		echo
+		chmod 755 ./"$config"/"$pack_d"_pack_e2fsdroid.sh && . ./"$config"/"$pack_d"*_pack_e2fsdroid.sh
+		if [ $(echo $?) -eq 0 ]; then
 
- busybox seq 3 | busybox xargs -I{} resize2fs -M "$outdir"/"$pack_d".new.img {} &>/dev/null
- 
- if [ "$sparse_e2fs" == "1" ]; then
- echo
- echo ".....Конвертация в sparse..."
- #echo
- size_out="$(busybox stat -c %s "$outdir"/"$pack_d".new.img)"
- img2simg "$outdir"/"$pack_d".new.img "$outdir"/"$pack_d".sparse.img
- if [ $(echo $?) -eq 0 ]; then
- busybox mv -f "$outdir"/"$pack_d".sparse.img "$outdir"/"$pack_d".new.img
- else
- echo
- echo ".....Ошибка при конвертации!"
- echo
- fi
- else
- size_out="$(busybox stat -c %s "$outdir"/"$pack_d".new.img)"
- fi
- if busybox test -s ./"$config"/"$pack_d"*_avb.img; then
-echo
- echo ".....Создание структуры AVB..."
- 
- #echo "avbtool add_hashtree_footer --image "$outdir"/"$pack_d".new.img --partition_size="$(busybox cat "$config"/"$pack_d"_size.txt)" "$part_name" --do_not_generate_fec "$prop_avb" "$sign_print" "$sign_file"" > ./"$config"/"$pack_d"_pack_avb_e2fsdroid.sh
- 
- echo "avbtool add_hashtree_footer --image "$outdir"/"$pack_d".new.img "$part_name" --do_not_generate_fec "$prop_avb" "$sign_print" "$sign_file"" > ./"$config"/"$pack_d"_pack_avb_e2fsdroid.sh
- 
- chmod 755 ./"$config"/"$pack_d"_pack_avb_e2fsdroid.sh && . ./"$config"/"$pack_d"*_pack_avb_e2fsdroid.sh
- 
-  if [ $(echo $?) -eq 0 ]; then
- size_out="$(avbtool info_image --image "$outdir"/"$pack_d".new.img | busybox awk '/^Image size:/ { print $3 }')"
- size_output_raw
- else
- echo
- echo ".....error: Ошибка при создании структуры AVB!"
- echo
- fi
- else
- size_output_raw
- fi
- else
- echo
- echo ".....error: Ошибка при сборке!"
- echo
-fi
- else
- echo
- echo ".....Ошибка! Не хватает файлов конфигурации"
- echo
- fi
+			busybox seq 3 | busybox xargs -I{} resize2fs -M "$outdir"/"$pack_d".new.img {} &>/dev/null
+
+			if [ "$sparse_e2fs" == "1" ]; then
+				echo
+				echo ".....Конвертация в sparse..."
+				#echo
+				size_out="$(busybox stat -c %s "$outdir"/"$pack_d".new.img)"
+				img2simg "$outdir"/"$pack_d".new.img "$outdir"/"$pack_d".sparse.img
+				if [ $(echo $?) -eq 0 ]; then
+					busybox mv -f "$outdir"/"$pack_d".sparse.img "$outdir"/"$pack_d".new.img
+				else
+					echo
+					echo ".....Ошибка при конвертации!"
+					echo
+				fi
+			else
+				size_out="$(busybox stat -c %s "$outdir"/"$pack_d".new.img)"
+			fi
+			if busybox test -s ./"$config"/"$pack_d"*_avb.img; then
+				echo
+				echo ".....Создание структуры AVB..."
+
+				#echo "avbtool add_hashtree_footer --image "$outdir"/"$pack_d".new.img --partition_size="$(busybox cat "$config"/"$pack_d"_size.txt)" "$part_name" --do_not_generate_fec "$prop_avb" "$sign_print" "$sign_file"" > ./"$config"/"$pack_d"_pack_avb_e2fsdroid.sh
+
+				echo "avbtool add_hashtree_footer --image "$outdir"/"$pack_d".new.img "$part_name" --do_not_generate_fec "$prop_avb" "$sign_print" "$sign_file"" >./"$config"/"$pack_d"_pack_avb_e2fsdroid.sh
+
+				chmod 755 ./"$config"/"$pack_d"_pack_avb_e2fsdroid.sh && . ./"$config"/"$pack_d"*_pack_avb_e2fsdroid.sh
+
+				if [ $(echo $?) -eq 0 ]; then
+					size_out="$(avbtool info_image --image "$outdir"/"$pack_d".new.img | busybox awk '/^Image size:/ { print $3 }')"
+					size_output_raw
+				else
+					echo
+					echo ".....error: Ошибка при создании структуры AVB!"
+					echo
+				fi
+			else
+				size_output_raw
+			fi
+		else
+			echo
+			echo ".....error: Ошибка при сборке!"
+			echo
+		fi
+	else
+		echo
+		echo ".....Ошибка! Не хватает файлов конфигурации"
+		echo
+	fi
 else
-echo
-echo ".....Нет папки \""$pack_d"\" для сборки образа, или файла *_pack_e2fsdroid.sh."
-echo
+	echo
+	echo ".....Нет папки \""$pack_d"\" для сборки образа, или файла *_pack_e2fsdroid.sh."
+	echo
 fi
 #busybox rm -f ./fs_config ./file_contexts
